// <auto-generated />
namespace WebApplication2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.2")]
    public sealed partial class AddConcurrentSessions : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddConcurrentSessions));
        
        string IMigrationMetadata.Id
        {
            get { return "202605051602318_AddConcurrentSessions"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
